"""
emailer.py — zip output files and send as an email attachment.

Three delivery methods are supported (select with --emailMethod):

  smtp          Standard SMTP. Credentials are optional for unauthenticated
                relays (e.g. institutional servers).  When required, set:
                  ONT_QC_SMTP_USER   SMTP username
                  ONT_QC_SMTP_PASS   SMTP password

  sendmail      Pipes the message to the local sendmail/postfix binary.
                Requires no credentials — the system MTA handles delivery.
                Works on most Linux lab servers and macOS.

  gmail-oauth   Sends via the Gmail API using OAuth2.  No password is ever
                stored.  On the first run a browser window opens for a
                one-time Google sign-in; the token is then cached at
                  ~/.config/ont_qc/gmail_token.json
                and refreshed automatically on subsequent runs.
                Requires:  pip install google-auth-oauthlib google-api-python-client
                Pass --gmailCredentials /path/to/credentials.json
                (downloaded from Google Cloud Console → OAuth2 → Desktop app).
"""

import base64
import os
import subprocess
import zipfile
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import encoders


# ---------------------------------------------------------------------------
# Helpers shared by all methods
# ---------------------------------------------------------------------------

def zip_outputs(outdir, run_name):
    """
    Create a zip of all PNG, HTML, and TXT files in outdir.
    Returns the path to the zip file.
    """
    prefix = f'{run_name}_' if run_name else ''
    zip_path = os.path.join(outdir, f'{prefix}qc_report.zip')
    extensions = {'.png', '.html', '.txt'}

    with zipfile.ZipFile(zip_path, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
        for fname in sorted(os.listdir(outdir)):
            if os.path.splitext(fname)[1].lower() in extensions:
                zf.write(os.path.join(outdir, fname), arcname=fname)

    size_mb = os.path.getsize(zip_path) / 1e6
    print(f'[ont_qc] Zip created: {zip_path} ({size_mb:.1f} MB)')
    return zip_path


def _build_message(smtp_from, recipient, run_name, zip_path):
    """Assemble a MIMEMultipart message with the zip attached."""
    subject = f'ONT QC Report — {run_name}' if run_name else 'ONT QC Report'
    body = (
        f'Please find the QC report for run "{run_name}" attached.\n\n'
        f'The zip contains all plot PNG files, the HTML report, and the '
        f'summary statistics text file.\n\n'
        f'Generated by ont_qc.py'
    )
    msg = MIMEMultipart()
    msg['From']    = smtp_from
    msg['To']      = recipient
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))

    with open(zip_path, 'rb') as fh:
        part = MIMEBase('application', 'zip')
        part.set_payload(fh.read())
    encoders.encode_base64(part)
    part.add_header(
        'Content-Disposition',
        f'attachment; filename="{os.path.basename(zip_path)}"',
    )
    msg.attach(part)
    return msg


# ---------------------------------------------------------------------------
# Method 1 — SMTP (with optional credentials)
# ---------------------------------------------------------------------------

def _send_smtp(recipient, zip_path, run_name, smtp_host, smtp_port, smtp_from,
               smtp_user=None, smtp_pass=None):
    import smtplib

    smtp_user = smtp_user or os.environ.get('ONT_QC_SMTP_USER', '')
    smtp_pass = smtp_pass or os.environ.get('ONT_QC_SMTP_PASS', '')

    msg = _build_message(smtp_from, recipient, run_name, zip_path)

    if smtp_port == 465:
        ctx = smtplib.SMTP_SSL(smtp_host, smtp_port)
    else:
        ctx = smtplib.SMTP(smtp_host, smtp_port)

    with ctx as server:
        server.ehlo()
        if smtp_port == 587:
            server.starttls()
            server.ehlo()
        if smtp_user:
            server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_from, recipient, msg.as_string())

    print(f'[ont_qc] Email sent via SMTP to {recipient}')


# ---------------------------------------------------------------------------
# Method 2 — sendmail binary (no credentials)
# ---------------------------------------------------------------------------

def _send_sendmail(recipient, zip_path, run_name, smtp_from):
    """
    Pipe the message to the local sendmail binary.
    Works on any Unix system with postfix/sendmail installed and configured.
    """
    # Find the binary
    candidates = ['/usr/sbin/sendmail', '/usr/bin/sendmail', '/usr/local/sbin/sendmail']
    binary = next((p for p in candidates if os.path.isfile(p)), None)
    if binary is None:
        # Try via PATH
        result = subprocess.run(['which', 'sendmail'], capture_output=True, text=True)
        binary = result.stdout.strip() or None

    if not binary:
        raise FileNotFoundError(
            'sendmail binary not found. Install postfix/sendmail or use --emailMethod smtp.'
        )

    msg = _build_message(smtp_from, recipient, run_name, zip_path)

    proc = subprocess.run(
        [binary, '-t', '-oi'],
        input=msg.as_bytes(),
        capture_output=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f'sendmail exited with code {proc.returncode}: {proc.stderr.decode()}'
        )

    print(f'[ont_qc] Email sent via sendmail to {recipient}')


# ---------------------------------------------------------------------------
# Method 3 — Gmail OAuth2 (no password, one-time browser authorisation)
# ---------------------------------------------------------------------------

_GMAIL_SCOPES    = ['https://www.googleapis.com/auth/gmail.send']
_TOKEN_DIR       = os.path.expanduser('~/.config/ont_qc')
_TOKEN_FILE      = os.path.join(_TOKEN_DIR, 'gmail_token.json')


def _send_gmail_oauth(recipient, zip_path, run_name, smtp_from, credentials_file):
    """
    Send via the Gmail API using OAuth2.

    credentials_file : path to credentials.json downloaded from:
      Google Cloud Console → APIs & Services → Credentials
      → Create Credentials → OAuth client ID → Desktop app → Download JSON

    The access token is cached at ~/.config/ont_qc/gmail_token.json and
    refreshed automatically on subsequent runs — no sign-in needed after
    the first use.
    """
    try:
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from googleapiclient.discovery import build
    except ImportError:
        raise ImportError(
            'Gmail OAuth2 requires additional packages:\n'
            '  pip install google-auth-oauthlib google-api-python-client'
        )

    if not credentials_file or not os.path.isfile(credentials_file):
        raise FileNotFoundError(
            f'Gmail credentials file not found: {credentials_file!r}\n'
            'Download credentials.json from Google Cloud Console:\n'
            '  APIs & Services → Credentials → OAuth client ID → Desktop app'
        )

    # Load or refresh token
    creds = None
    if os.path.isfile(_TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(_TOKEN_FILE, _GMAIL_SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(credentials_file, _GMAIL_SCOPES)
            creds = flow.run_local_server(port=0)
        os.makedirs(_TOKEN_DIR, exist_ok=True)
        with open(_TOKEN_FILE, 'w') as fh:
            fh.write(creds.to_json())

    # Build the raw RFC-2822 message and base64-encode it for the API
    msg = _build_message(smtp_from, recipient, run_name, zip_path)
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()

    service = build('gmail', 'v1', credentials=creds)
    service.users().messages().send(
        userId='me',
        body={'raw': raw},
    ).execute()

    print(f'[ont_qc] Email sent via Gmail OAuth2 to {recipient}')


# ---------------------------------------------------------------------------
# Public dispatch function
# ---------------------------------------------------------------------------

def send_email(recipient, zip_path, run_name, method,
               smtp_host='localhost', smtp_port=25, smtp_from='ont_qc@localhost',
               smtp_user=None, smtp_pass=None,
               gmail_credentials=None):
    """
    Send the zipped QC report by email.

    method : 'smtp' | 'sendmail' | 'gmail-oauth'
    """
    if method == 'sendmail':
        _send_sendmail(recipient, zip_path, run_name, smtp_from)

    elif method == 'gmail-oauth':
        _send_gmail_oauth(recipient, zip_path, run_name, smtp_from, gmail_credentials)

    elif method == 'smtp':
        _send_smtp(recipient, zip_path, run_name, smtp_host, smtp_port, smtp_from,
                   smtp_user=smtp_user, smtp_pass=smtp_pass)

    else:
        raise ValueError(f'Unknown email method: {method!r}. '
                         f'Choose smtp, sendmail, or gmail-oauth.')
