"""
HTML report builder.

Generates a self-contained HTML file with embedded base64 images and a
summary statistics table. No external CSS/JS dependencies.
"""

import base64
import os
from datetime import datetime


# ---------------------------------------------------------------------------
# HTML template fragments
# ---------------------------------------------------------------------------

_PAGE_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ONT QC Report – {run_name}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f5f5f5; color: #333; }}
    header {{ background: #1565C0; color: white; padding: 24px 32px; }}
    header h1 {{ font-size: 1.8em; }}
    header p  {{ font-size: 0.9em; opacity: 0.85; margin-top: 4px; }}
    main {{ max-width: 1400px; margin: 24px auto; padding: 0 24px 48px; }}
    section {{ margin-bottom: 40px; }}
    h2 {{ font-size: 1.3em; color: #1565C0; border-bottom: 2px solid #1565C0;
          padding-bottom: 6px; margin-bottom: 16px; }}
    .stats-table {{ border-collapse: collapse; width: 100%; max-width: 640px;
                    background: white; border-radius: 6px; overflow: hidden;
                    box-shadow: 0 1px 4px rgba(0,0,0,.12); }}
    .stats-table th, .stats-table td {{ padding: 10px 16px; text-align: left;
                                         font-size: 0.95em; }}
    .stats-table tr:nth-child(even) {{ background: #f0f4ff; }}
    .stats-table th {{ background: #1565C0; color: white; }}
    .plot-grid {{ display: flex; flex-wrap: wrap; gap: 20px; }}
    .plot-card {{ background: white; border-radius: 8px;
                  box-shadow: 0 1px 4px rgba(0,0,0,.12); overflow: hidden;
                  flex: 1 1 580px; max-width: 780px; }}
    .plot-card img {{ width: 100%; display: block; }}
    .plot-card p {{ padding: 8px 14px; font-size: 0.85em; color: #666; }}
    .video-card {{ background: white; border-radius: 8px;
                   box-shadow: 0 1px 4px rgba(0,0,0,.12); overflow: hidden;
                   width: 100%; }}
    .video-card video, .video-card img {{ width: 100%; display: block; }}
    .video-card p {{ padding: 8px 14px; font-size: 0.85em; color: #666; }}
    .plotly-card {{ background: white; border-radius: 8px;
                    box-shadow: 0 1px 4px rgba(0,0,0,.12); overflow: hidden;
                    width: 100%; padding: 8px; }}
    .reads-table {{ border-collapse: collapse; width: 100%; max-width: 860px;
                    background: white; border-radius: 6px; overflow: hidden;
                    box-shadow: 0 1px 4px rgba(0,0,0,.12); font-family: monospace; }}
    .reads-table th, .reads-table td {{ padding: 9px 16px; text-align: left; font-size: 0.9em; }}
    .reads-table tr:nth-child(even) {{ background: #f0f4ff; }}
    .reads-table th {{ background: #1565C0; color: white; font-family: 'Segoe UI', Arial, sans-serif; }}
    footer {{ text-align: center; font-size: 0.8em; color: #999; padding: 16px; }}
  </style>
</head>
<body>
<header>
  <h1>ONT QC Report</h1>
  <p>Run: {run_name} &nbsp;|&nbsp; Generated: {generated}</p>
</header>
<main>
{sections}
</main>
<footer>Generated by ont_qc.py</footer>
</body>
</html>
"""

_SECTION_TEMPLATE = """\
<section>
  <h2>{title}</h2>
  {content}
</section>
"""

_PLOT_GRID_TEMPLATE = '<div class="plot-grid">{cards}</div>'

_PLOT_CARD_TEMPLATE = """\
<div class="plot-card">
  <img src="data:image/png;base64,{b64}" alt="{caption}">
  <p>{caption}</p>
</div>
"""

_VIDEO_CARD_MP4_TEMPLATE = """\
<div class="video-card">
  <video controls loop autoplay muted onloadedmetadata="this.playbackRate=1.75;">
    <source src="data:video/mp4;base64,{b64}" type="video/mp4">
    Your browser does not support embedded video.
  </video>
  <p>{caption}</p>
</div>
"""

_VIDEO_CARD_GIF_TEMPLATE = """\
<div class="video-card">
  <img src="data:image/gif;base64,{b64}" alt="{caption}">
  <p>{caption}</p>
</div>
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _img_to_b64(path):
    with open(path, 'rb') as fh:
        return base64.b64encode(fh.read()).decode('ascii')


def _video_section(video_path):
    """Return an HTML section string embedding the video as base64."""
    if not video_path or not os.path.isfile(video_path):
        return ''
    b64 = _img_to_b64(video_path)
    caption = 'Per-channel strand time animated over run time (1 frame = 1 hour)'
    if video_path.endswith('.mp4'):
        card = _VIDEO_CARD_MP4_TEMPLATE.format(b64=b64, caption=caption)
    else:
        card = _VIDEO_CARD_GIF_TEMPLATE.format(b64=b64, caption=caption)
    return _SECTION_TEMPLATE.format(title='Channel Strand-Time Animation', content=card)


def _stats_table(stats):
    rows = [
        ('Run time',              f"{stats['run_time_hr']} hr"),
        ('Pores available @ T=0', f"{stats.get('pores_t0', 'N/A'):,}"),
        ('Total reads',           f"{stats['total_reads']:,}"),
        ('Pass-filter reads',     f"{stats['pf_reads']:,}"),
        ('% pass-filter',         f"{stats['pct_pf']} %"),
        ('Total yield',           f"{stats['yield_gb']} Gb"),
        ('Pass-filter yield',     f"{stats['pf_yield_gb']} Gb"),
        ('N50',                   f"{stats['n50']:,} bp" if stats['n50'] else 'N/A'),
        ('Mean PF read length',   f"{stats['mean_read_length']:,} bp"),
        ('SD PF read length',     f"{stats['sd_read_length']:,} bp"),
        ('Longest PF read',       f"{stats['max_read_length']:,} bp"),
        ('Mean PF Q-score',       str(stats['mean_qscore'])),
        (f"Prop. bases ≥ {stats['cutoff_length']:,} bp",
                                  str(stats['prop_above_cutoff'])),
    ]
    tbody = ''.join(
        f'<tr><td>{k}</td><td>{v}</td></tr>' for k, v in rows
    )
    return (
        '<table class="stats-table">'
        '<thead><tr><th>Metric</th><th>Value</th></tr></thead>'
        f'<tbody>{tbody}</tbody>'
        '</table>'
    )


def _top_reads_table(top10_df):
    """Render the top-10 longest reads as a simple HTML table."""
    if top10_df is None or top10_df.empty:
        return '<p>No pass-filter reads found.</p>'
    rows = ''
    for rank, row in top10_df.iterrows():
        length = f"{int(row['sequence_length_template']):,}"
        rows += f'<tr><td>{rank}</td><td>{row["read_id"]}</td><td>{length}</td></tr>'
    return (
        '<table class="reads-table">'
        '<thead><tr><th>#</th><th>Read ID</th><th>Length (bp)</th></tr></thead>'
        f'<tbody>{rows}</tbody>'
        '</table>'
    )


def _plot_cards(paths_captions):
    """paths_captions: list of (path, caption) tuples. Skip None paths."""
    cards = []
    for path, caption in paths_captions:
        if path and os.path.isfile(path):
            b64 = _img_to_b64(path)
            cards.append(_PLOT_CARD_TEMPLATE.format(b64=b64, caption=caption))
    return _PLOT_GRID_TEMPLATE.format(cards='\n'.join(cards))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_report(stats, plot_registry, outpath, run_name, video_path=None,
                 plotly_sections=None):
    """
    Build a self-contained HTML QC report.

    Parameters
    ----------
    stats : dict
        Output of stats.compute_stats().
    plot_registry : dict
        Keys are section names; values are lists of (filepath, caption) tuples.
        Recognised section keys (in order):
          'throughput', 'read_quality', 'channel_map', 'barcodes', 'duty_time'
    outpath : str
        Destination HTML file path.
    run_name : str
        Run identifier shown in the report header.
    """
    sections_html = []

    # 1. Summary statistics
    sections_html.append(
        _SECTION_TEMPLATE.format(
            title='Run Summary',
            content=_stats_table(stats),
        )
    )

    # 2. Ordered plot sections
    section_order = [
        ('throughput',   'Throughput'),
        ('run_health',   'Run Health over Time'),
        ('read_quality', 'Read Quality'),
        ('channel_map',  'Flowcell Channel Map'),
        ('barcodes',     'Barcode Analysis'),
        ('duty_time',    'Pore Activity / Duty Time'),
    ]

    plotly_sections = plotly_sections or {}

    for key, title in section_order:
        if key in plotly_sections and plotly_sections[key]:
            # Plotly chart first; any additional static PNGs (e.g. occupancy) follow
            parts = [f'<div class="plotly-card">{plotly_sections[key]}</div>']
            if key in plot_registry and plot_registry[key]:
                parts.append(
                    f'<div style="margin-top: 20px;">{_plot_cards(plot_registry[key])}</div>'
                )
            sections_html.append(
                _SECTION_TEMPLATE.format(title=title, content=''.join(parts))
            )
        elif key in plot_registry and plot_registry[key]:
            content = _plot_cards(plot_registry[key])
            if content.strip():
                sections_html.append(
                    _SECTION_TEMPLATE.format(title=title, content=content)
                )
        # Insert video section after channel map
        if key == 'channel_map':
            vid_html = _video_section(video_path)
            if vid_html:
                sections_html.append(vid_html)

    # Last section: top-10 longest reads
    sections_html.append(
        _SECTION_TEMPLATE.format(
            title='Top 10 Longest Pass-Filter Reads',
            content=_top_reads_table(stats.get('top10_reads')),
        )
    )

    html = _PAGE_TEMPLATE.format(
        run_name=run_name or 'Unknown',
        generated=datetime.now().strftime('%Y-%m-%d %H:%M'),
        sections='\n'.join(sections_html),
    )

    with open(outpath, 'w', encoding='utf-8') as fh:
        fh.write(html)

    return outpath
